package org.upkaari.api.common.auditlog;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.validation.constraints.Size;

import org.eclipse.microprofile.openapi.annotations.media.Schema;
import org.upkaari.api.common.annotations.AutoGeneratedUUID;
import org.upkaari.api.common.constants.Views;

import com.fasterxml.jackson.annotation.JsonView;

@Entity(name = "AUDIT_LOG")
public class AuditLog {

	@Id
	@AutoGeneratedUUID
	@Column(name = "AUDIT_ID")
	@JsonView(value= {Views.Allways.class})
	@Schema(description = "Autogenerated nemeric id of the change history entry",required=true)
	private String id;
	@Column(name = "ACTION")
	@Size(max = 20, min=1)
	@JsonView(value= {Views.Allways.class})
	@Schema(description = "Action performed on the entity i.e. Add, Update, Delete",required=true,example = "Update")
	private String action;
	@Column(name = "ACTION_DATE")
	@JsonView(value= {Views.Allways.class})
	@Schema(description = "Date of action",required=true)
	private Date date;
	@Column(name = "ACTION_USER")
	@Size(max = 20, min=1)
	@JsonView(value= {Views.Allways.class})
	@Schema(description = "User name who performed the action",required=true)
	private String user;
	@Column(name = "OBJ_TYPE")
	@Size(max = 50, min=1)
	@JsonView(value= {Views.Allways.class})
	@Schema(description = "Entity/Resource type e.g. Components, Releases etc.",required=true)
	private String objectType;
	@Column(name = "OBJ_NAME")
	@Size(max = 500, min=1)
	@JsonView(value= {Views.Allways.class})
	@Schema(description = "Human readable description of the entity/resource",required=true)
	private String objectName;
	@Column(name = "OBJ_ID")
	@Size(max = 100, min=1)
	@JsonView(value= {Views.Allways.class})
	@Schema(description = "Id of the entity/resource",required=true)
	private String objectId;
	@Column(name = "ACTION_DETAILS")
	@Size(min=0)
	@JsonView(value= {Views.Allways.class})
	@Schema(description = "Details of changes made to entity/resource. It is a variable length string stored as CLOB")
	private String details;
	
	@Column(name = "FILTER_VALUE")
	@Size(max = 100, min=1)
	@JsonView(value= {Views.Allways.class})
	@Schema(description = "Filter value",required=false)
	private String filterValue;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getObjectType() {
		return objectType;
	}

	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	public String getObjectName() {
		return objectName;
	}

	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	public String getObjectId() {
		return objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	public String getDetails() {
		return details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	public String getFilterValue() {
		return filterValue;
	}

	public void setFilterValue(String filterValue) {
		this.filterValue = filterValue;
	}
	
}