package org.upkaari.api.common.domain;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.validation.constraints.Size;

import org.eclipse.microprofile.openapi.annotations.media.Schema;
import org.upkaari.api.common.annotations.AutoGeneratedUUID;
import org.upkaari.api.common.annotations.LifecycleStatus;
import org.upkaari.api.common.constants.Views;

import com.fasterxml.jackson.annotation.JsonView;

@MappedSuperclass
public abstract class AbstractResource<ID extends Serializable> implements IdentifiableEntity<ID> {

	@Id
	@Column(name="ID")
	@Schema(description = "Internal ID", required=true)
	@JsonView(value = {Views.List.class})
	@AutoGeneratedUUID
	private ID id;
	
	@Column(name="CREATE_DATE")
	@JsonView(value=Views.List.class)
	@Schema(description = "Date when this record was created")
	private Date createDate;
	
	@Column(name="CREATE_USER")
	@JsonView(value=Views.List.class)
	@Size(min = 1, max = 50)
	@Schema(description = "User who created this record.")
	private String createUser;

	@Column(name="IS_DISABLED")
	@Schema(description = "'true' if the entry is disabled i.e. not in use",example = "false")
	@JsonView(value= {Views.Update.class,Views.List.class})
	@LifecycleStatus	
	private Boolean isDisabled;	
	
	public Date getCreateDate() {
		return createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	public String getCreateUser() {
		return createUser;
	}
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}
	public ID getId() {
		return id;
	}
	public void setId(ID id) {
		this.id = id;
	}
	public Boolean getIsDisabled() {
		return isDisabled;
	}
	public void setIsDisabled(Boolean isDisabled) {
		this.isDisabled = isDisabled;
	}

}
